# Copyright © 2001 by the Rectors and Visitors of the University of Virginia. 

# Extend Ubunto 20.04

FROM docker.io/kevinsullivan/leanvm:latest

# Your extensions to your environment can go here.
# Then you must rebuild the container. You probably
# don't need to do anything here at all, but if you
# find a great improvement to the environment, or a
# bug fix, please send a pull request to upstreeam.
# If you don't know what that means, no worries, you
# can just ignore it.
#
